# Generated by Django 2.0.1 on 2018-02-04 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screeni', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoSlide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('application_deadline', models.DateField(blank=True, null=True)),
                ('image', models.FileField(null=True, upload_to='promo_images/')),
            ],
        ),
        migrations.DeleteModel(
            name='AdSlide',
        ),
    ]
