# Generated by Django 2.0.1 on 2018-02-12 18:50

from django.db import migrations
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('screeni', '0002_auto_20180204_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promoslide',
            name='description',
            field=martor.models.MartorField(),
        ),
    ]
