# Generated by Django 2.0.1 on 2018-02-12 19:06

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('screeni', '0003_auto_20180212_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promoslide',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
