# Generated by Django 2.0.1 on 2018-02-12 22:22

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('screeni', '0004_auto_20180212_1906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promoslide',
            name='application_deadline',
        ),
        migrations.RemoveField(
            model_name='promoslide',
            name='image',
        ),
        migrations.AlterField(
            model_name='promoslide',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
