# Generated by Django 2.0.1 on 2018-02-13 15:34

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screeni', '0005_auto_20180212_2222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentslide',
            name='ingress',
        ),
        migrations.AlterField(
            model_name='contentslide',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='contentslide',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='promoslide',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
