# Generated by Django 2.0.1 on 2018-02-15 10:23

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentSlide',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('display_duration', models.DurationField(default=datetime.timedelta(0, 10))),
                ('start_hour', models.TimeField(default=datetime.time(0, 0))),
                ('end_hour', models.TimeField(default=datetime.time(23, 59, 59))),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
        migrations.CreateModel(
            name='PromoSlide',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('display_duration', models.DurationField(default=datetime.timedelta(0, 10))),
                ('start_hour', models.TimeField(default=datetime.time(0, 0))),
                ('end_hour', models.TimeField(default=datetime.time(23, 59, 59))),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
    ]
