# Generated by Django 2.0.1 on 2018-02-15 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('screeni', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentslide',
            name='end_hour',
        ),
        migrations.RemoveField(
            model_name='contentslide',
            name='start_hour',
        ),
        migrations.RemoveField(
            model_name='promoslide',
            name='end_hour',
        ),
        migrations.RemoveField(
            model_name='promoslide',
            name='start_hour',
        ),
    ]
