# Generated by Django 2.0.1 on 2018-02-25 11:32

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screeni', '0004_auto_20180224_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('title', models.CharField(max_length=255)),
                ('display_duration', models.PositiveSmallIntegerField(default=15)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
        migrations.DeleteModel(
            name='ContentSlide',
        ),
        migrations.DeleteModel(
            name='PromoSlide',
        ),
    ]
